INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_01', 'Working', 'ic_doing_working', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_02', 'Gaming', 'ic_doing_game', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_03', 'Hiking', 'ic_doing_hiking', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_04', 'Photograph', 'ic_doing_photograph', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_05', 'Travel', 'ic_doing_travel', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_06', 'Coffee', 'ic_doing_drink_coffee', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_07', 'Eat healthy', 'ic_doing_eat_healthy', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_08', 'Beer', 'ic_doing_drink_beer', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_09', 'Sleep well', 'ic_doing_sleep_early', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_10', 'Reading', 'ic_doing_reading', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_11', 'Painting', 'ic_doing_painting', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_12', 'Party', 'ic_doing_party', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_13', 'Sports', 'ic_doing_sporting', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_14', 'Pet', 'ic_doing_pet', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_15', 'Music', 'ic_doing_music', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_16', 'Moive', 'ic_doing_movie', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_17', 'Meeting', 'ic_doing_meeting', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_18', 'Hospital', 'ic_doing_hospital', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_19', 'Income', 'ic_doing_income', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('doing_20', 'Dating', 'ic_doing_dating', 'doing');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('mood_01', 'Rad', 'ic_mood_excited', 'mood');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('mood_02', 'Good', 'ic_mood_good', 'mood');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('mood_03', 'Mes', 'ic_mood_meh', 'mood');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('mood_04', 'Bad', 'ic_mood_bad', 'mood');
INSERT INTO `type` (`code`, `name`, `icon`, `category`) VALUES ('mood_05', 'Awful', 'ic_mood_awful', 'mood');
